[project]
name = "copy-by-date"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pillow>=11.3.0"]

[dependency-groups]
dev = ["pyright>=1.1.407"]

[tool.pyright]
typeCheckingMode = "strict"
